package gd.zh.gamer.scorer.db;

import gd.zh.gamer.scorer.entity.Authorization;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHORIZATION".
*/
public class AuthorizationDao extends AbstractDao<Authorization, Long> {

    public static final String TABLENAME = "AUTHORIZATION";

    /**
     * Properties of entity Authorization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Printer_id = new Property(1, Long.class, "printer_id", false, "PRINTER_ID");
        public final static Property Operator_id = new Property(2, Long.class, "operator_id", false, "OPERATOR_ID");
    };


    public AuthorizationDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHORIZATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PRINTER_ID\" INTEGER," + // 1: printer_id
                "\"OPERATOR_ID\" INTEGER);"); // 2: operator_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHORIZATION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Authorization entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long printer_id = entity.getPrinter_id();
        if (printer_id != null) {
            stmt.bindLong(2, printer_id);
        }
 
        Long operator_id = entity.getOperator_id();
        if (operator_id != null) {
            stmt.bindLong(3, operator_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Authorization readEntity(Cursor cursor, int offset) {
        Authorization entity = new Authorization( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // printer_id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // operator_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Authorization entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPrinter_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOperator_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Authorization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Authorization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
