package gd.zh.gamer.scorer.db;

import gd.zh.gamer.scorer.entity.Account;
import gd.zh.gamer.scorer.entity.Printer;
import gd.zh.gamer.scorer.entity.Record;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig printerDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final AccountDao accountDao;
    private final PrinterDao printerDao;
    private final RecordDao recordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        printerDaoConfig = daoConfigMap.get(PrinterDao.class).clone();
        printerDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        printerDao = new PrinterDao(printerDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Printer.class, printerDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        printerDaoConfig.getIdentityScope().clear();
        recordDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public PrinterDao getPrinterDao() {
        return printerDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
