package gd.zh.gamer.scorer.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUTHORIZATION".
 */
public class Authorization {

    private Long id;
    private Long printer_id;
    private Long operator_id;

    public Authorization() {
    }

    public Authorization(Long id) {
        this.id = id;
    }

    public Authorization(Long id, Long printer_id, Long operator_id) {
        this.id = id;
        this.printer_id = printer_id;
        this.operator_id = operator_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPrinter_id() {
        return printer_id;
    }

    public void setPrinter_id(Long printer_id) {
        this.printer_id = printer_id;
    }

    public Long getOperator_id() {
        return operator_id;
    }

    public void setOperator_id(Long operator_id) {
        this.operator_id = operator_id;
    }

}
