package gd.zh.gamer.scorer.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRINTER".
 */
public class Printer {

    private Long id;
    /** Not-null value. */
    private String sn;
    private String name;
    private Long manager_id;

    public Printer() {
    }

    public Printer(Long id) {
        this.id = id;
    }

    public Printer(Long id, String sn, String name, Long manager_id) {
        this.id = id;
        this.sn = sn;
        this.name = name;
        this.manager_id = manager_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSn() {
        return sn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSn(String sn) {
        this.sn = sn;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getManager_id() {
        return manager_id;
    }

    public void setManager_id(Long manager_id) {
        this.manager_id = manager_id;
    }

}
