package gd.zh.gamer.scorer.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD".
 */
public class Record {

    private Long id;
    private int score;
    private long print_time;
    private long exc_time;
    private Long printer_id;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, int score, long print_time, long exc_time, Long printer_id) {
        this.id = id;
        this.score = score;
        this.print_time = print_time;
        this.exc_time = exc_time;
        this.printer_id = printer_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public long getPrint_time() {
        return print_time;
    }

    public void setPrint_time(long print_time) {
        this.print_time = print_time;
    }

    public long getExc_time() {
        return exc_time;
    }

    public void setExc_time(long exc_time) {
        this.exc_time = exc_time;
    }

    public Long getPrinter_id() {
        return printer_id;
    }

    public void setPrinter_id(Long printer_id) {
        this.printer_id = printer_id;
    }

}
